const REQUEST_LOGIN = "REQUEST_LOGIN"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAIL = "LOGIN_FAIL"
const LOGOUT = "LOGOUT"

export {
  REQUEST_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT
}