const REQUEST_PROFILE = "REQUEST_PROFILE"
const UPDATE_PROFILE = "UPDATE_PROFILE"
const PROFILE_RECEIVED = "PROFILE_RECEIVED"
const PROFILE_UPDATED = "PROFILE_UPDATED"
const CREATE_PROFILE = "CREATE_PROFILE"
const PROFILE_CREATED = "PROFILE_CREATED"
const DELETE_PROFILE = "DELETE_PROFILE"
const PROFILE_DELETED = "PROFILE_DELETED"

export {
  REQUEST_PROFILE,
  UPDATE_PROFILE,
  PROFILE_RECEIVED,
  PROFILE_UPDATED,
  CREATE_PROFILE,
  PROFILE_CREATED,
  DELETE_PROFILE,
  PROFILE_DELETED
}