const REQUEST_PROJECTS = "REQUEST_PROJECTS"
const UPDATE_PROJECT = "UPDATE_PROJECT"
const PROJECTS_RECEIVED = "PROJECTS_RECEIVED"
const PROJECT_UPDATED = "PROJECT_UPDATED"
const CREATE_PROJECT = "CREATE_PROJECT"
const PROJECT_CREATED = "PROJECT_CREATED"
const DELETE_PROJECT = "DELETE_PROJECT"
const PROJECT_DELETED = "PROJECT_DELETED"

export {
  REQUEST_PROJECTS,
  UPDATE_PROJECT,
  PROJECTS_RECEIVED,
  PROJECT_UPDATED,
  CREATE_PROJECT,
  PROJECT_CREATED,
  DELETE_PROJECT,
  PROJECT_DELETED
}